# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Continuous Integration"

on:
  - pull_request
  - push

permissions:
  contents: read

concurrency:
  group: "${{ github.event_name }}-${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  tests:
    name: "UnitTests with vitest"

    runs-on: "${{ matrix.operating-system }}"
    timeout-minutes: 10
    continue-on-error: false

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-20.04"
          - "ubuntu-22.04"

        node-version:
          - "16"
          - "18"
          - "19"
          - "20"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          lfs: false
          persist-credentials: false

      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: "actions/setup-node@v3"
        with:
          node-version: "${{ matrix.node-version }}"

      - name: "install dependencies"
        run: "npm install --frozen-lockfile"

      - name: "Generate coverage report"
        run: "npm run coverage"

      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v3.1.4"
        with:
          fail_ci_if_error: true
          file: ".reports/clover.xml"
          flags: "vitest,nodejs-${{ matrix.node-version }},${{ matrix.operating-system }}"
          verbose: false

  # This is a meta job to avoid to have to constantly change the protection rules
  # whenever we touch the matrix.
  tests-status:
    name: "Unit & Integration Tests Status"

    runs-on: "ubuntu-22.04"

    if: always()

    needs:
      - "tests"

    steps:
      - name: Successful run
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0

      - name: Failing run
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
